name: Fix Badges
description: Help us to fix the badges
labels: bug
body:
  - type: checkboxes
    attributes:
      label: Issue tracker rule checks (please read carefully)
      options:
        - label: "I have checked that my problem <a href='https://github.com/intergrav/devins-badges/issues' target='_blank'>is not already reported</a>"
          required: true
        - label: "I have checked that my problem is not already fixed"
          required: true
  - type: textarea
    attributes:
      label: Issue description
      description: Explain clearly what is wrong
    validations:
      required: true
